baseurl = "http://hannes.kaeufler.net"
languageCode = "en-us"
title = "A slow saturday"
pygmentsuseclasses = true

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Author = "Hannes Käufler"
GitHub = "https://github.com/hanneskaeufler"
Twitter = "https://twitter.com/hanneskaeufler"
Lang = "en-us"
