FROM crystallang/crystal:0.35.1

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get install -y nodejs postgresql-client && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /home/tmp && \
        cd /home/tmp && \
        git clone https://github.com/luckyframework/lucky_cli && \
        cd lucky_cli && \
        git checkout v0.22.0 && \
        shards install && \
        crystal build src/lucky.cr && \
        mv lucky /usr/local/bin/lucky

RUN cd /home/tmp && \
        curl -O https://bin.equinox.io/c/ekMN3bCZFUn/forego-stable-linux-amd64.tgz && \
        ls -la && \
        tar zxvf forego-stable-linux-amd64.tgz && \
        mv forego /usr/local/bin/forego

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

ENV NODE_ENV=development
RUN npm ci

COPY shard.yml shard.yml
COPY shard.lock shard.lock

ENV SKIP_LUCKY_TASK_PRECOMPILATION=true
RUN shards install

CMD ["sh", "-c", "lucky dev"]
