version: 2
jobs:
  build:
    docker:
      - image: hanneskaeufler/crystal-node-ruby
        environment:
          DATABASE_URL: postgres://blog_test_user@127.0.0.1/blog_test
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: blog_test
          POSTGRES_USER: blog_test_user
    steps:
      - checkout
      - run:
          name: "Install node dependencies"
          command: yarn install
      - run:
          name: "Compiling assets"
          command: ./bin/compile_assets build
      - run:
          name: "Install crystal dependencies"
          command: crystal deps
      - run:
          name: "Check formatting"
          command: crystal tool format src spec --check
      - run:
          name: "Migrate database"
          command: LUCKY_ENV=test crystal tasks.cr -- db.migrate
      - run:
          name: "Running specs"
          command: crystal spec --junit_output=/root/reports
      - store_test_results:
          path: /root/reports
          when: always
      - run:
          name: "Install rubygems"
          command: bundle
          when: always
      - run:
          name: "Run danger"
          command: bundle exec danger
          when: always
