version: 2
jobs:
  build:
    docker:
      - image: hanneskaeufler/crystal-node-ruby
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: blog_test
    steps:
      - checkout
      - run:
          name: "Install node dependencies"
          command: yarn install
      - run:
          name: "Compiling assets"
          command: ./bin/compile_assets build
      - run:
          name: "Install crystal dependencies"
          command: crystal deps
      - run:
          name: "Check formatting"
          command: crystal tool format src spec --check
      - run:
          name: "Migrate database"
          command: LUCKY_ENV=test crystal tasks.cr -- db.migrate
      - run:
          name: "Running specs"
          command: crystal spec
