version: 2
jobs:
  build:
    docker:
      - image: hanneskaeufler/crystal-node-ruby:0.24.1
        environment:
          DATABASE_URL: postgres://blog_test_user@127.0.0.1/blog_test
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: blog_test
          POSTGRES_USER: blog_test_user
    steps:
      - checkout
      - run:
          name: "Install node dependencies"
          command: yarn install
      - run:
          name: "Stylelint"
          command: "yarn lint"
      - run:
          name: "Compiling assets"
          command: yarn prod && yarn prod
      - run:
          name: "Install crystal dependencies"
          command: crystal deps
      - run:
          name: "Check formatting"
          command: crystal tool format src spec --check
      - run:
          name: "Static analysis"
          command: ./bin/ameba
      - run:
          name: "Migrate database"
          command: LUCKY_ENV=test crystal tasks.cr -- db.migrate
      - run:
          name: "Running specs"
          command: crystal spec --junit_output=/root/reports
      - run:
          name: "Fix crystal junit output bug. Remove for crystal 0.24.2"
          command: sed -i 's/failed=/failures=/g' /root/reports/output.xml
          when: always
      - store_test_results:
          path: /root/reports
          when: always
      - run:
          name: "Run danger"
          command: yarn danger ci
          when: always
      - run:
          name: "Run webserver"
          command: crystal --release ./src/app.cr
          background: true
      - run:
          name: "Run BackstopJS"
          command: yarn test
  deploy:
    docker:
      - image: hanneskaeufler/crystal-node-ruby:0.24.1
    steps:
      - checkout
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Deploy Master to Heroku
          command: |
            git push git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
