version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal
        environment:
          DATABASE_URL: postgres://blog-user@127.0.0.1/blog-test
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: blog-test
          POSTGRES_USER: blog-user
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: crystal deps
      - run:
          name: "Check formatting"
          command: crystal tool format src spec --check
      - run:
          name: "Migrate database"
          command: LUCKY_ENV=test lucky db.migrate
      - run:
          name: "Running specs"
          command: crystal spec
