#!/bin/sh

# Exit if any subcommand fails
set -e

indent() {
  while read LINE; do
    echo "  $LINE" || true
  done
}

if ! command -v npm > /dev/null; then
  printf 'NPM is not installed.\n'
  printf 'See https://docs.npmjs.com/cli/npm for install instructions.\n'
  exit 1
fi

echo -e "\n▸ Installing node dependencies"
npm ci | indent

echo -e "\n▸ Compiling assets"
npm run dev | indent

echo -e "\n▸ Installing shards"
crystal deps | indent

echo -e "\n▸ Checking that a process runner is installed"
# Only if this isn't CI
if [ -z "$CI" ]; then
  lucky ensure_process_runner_installed
fi
echo "✔ Done" | indent

echo -e "\n▸ Setting up the database"
lucky db.create | indent

echo -e "\n▸ Migrating the database"
lucky db.migrate | indent

echo -e "\n▸ Seed the database with required and sample records"
lucky db.required_seeds | indent
lucky db.helpful_seeds | indent

echo -e "\n✔ All done. Run 'lucky dev' to start the app"
