#!/usr/bin/env bash

echo "require \"./spec/**\"" > run_tests.cr && \
crystal build run_tests.cr && \
sudo kcov --clean --include-path=$(pwd)/src $(pwd)/coverage ./run_tests && \
bash <(curl -s https://codecov.io/bash) -s $(pwd)/coverage
