name: Danger

on:
  pull_request:
    branches: [ master ]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Danger JS Action
      uses: danger/danger-js@10.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
