name: nightly
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test-mutations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Setup
        run: ./script/setup
      - name: Mutation-Test
        run: ./script/test-mutation
